matrix:
    include:
    - env: version=0.10.2

dist: trusty
os:
    - linux-ppc64le
sudo: required
language: go
go:
- "1.12.1"

install:
    - sudo apt update
        - sudo apt install lftp
            - python3 ftp_version.py

script:
    - bash build.sh
